export default {
  // list
  BOTS_LIST_REQUEST: 'BOTS_LIST_REQUEST',
  BOTS_LIST_SUCCESS: 'BOTS_LIST_SUCCESS',
  BOTS_LIST_FAILURE: 'BOTS_LIST_FAILURE',

  // create
  BOTS_CREATE_REQUEST: 'BOTS_CREATE_REQUEST',
  BOTS_CREATE_SUCCESS: 'BOTS_CREATE_SUCCESS',
  BOTS_CREATE_FAILURE: 'BOTS_CREATE_FAILURE',

  // fetch
  BOTS_FETCH_REQUEST: 'BOTS_FETCH_REQUEST',
  BOTS_FETCH_SUCCESS: 'BOTS_FETCH_SUCCESS',
  BOTS_FETCH_FAILURE: 'BOTS_FETCH_FAILURE',

  // update
  BOTS_UPDATE_REQUEST: 'BOTS_UPDATE_REQUEST',
  BOTS_UPDATE_SUCCESS: 'BOTS_UPDATE_SUCCESS',
  BOTS_UPDATE_FAILURE: 'BOTS_UPDATE_FAILURE',

  // remove
  BOTS_REMOVE_REQUEST: 'BOTS_REMOVE_REQUEST',
  BOTS_REMOVE_SUCCESS: 'BOTS_REMOVE_SUCCESS',
  BOTS_REMOVE_FAILURE: 'BOTS_REMOVE_FAILURE',
};
